Module4 task1
htmlacademy-javascript/1778433-keksobooking-25 pull request #3
Opened 2022-02-28 10:02 UTC by semenov-vldr

Есть вопросы по заданию:
1. Значения **checkin** и **checkout** должны ли как-то зависеть друг от друга, например, **checkout** должен быть раньше или не позже, чем **checkin**? На данный момент я сделал их генерацию независимо и рандомно.
2. Не понял как на данном этапе записать значение для ключа **address**, оставил закомментированной строкой
3. Значение **price** должно быть от и до какого значения? Или это на мое усмотрение? 
4. Значения для ключа **photos** тоже не понял какое надо указать.
5. У меня браузер (точнее js) ругается на название ключа **location**, пишет, что уже задекларировано это имя уже (может это ключевое слово, которое нельзя использовать?), хотя странно. Поэтому сделал название пока что **locationn**.

2022-03-03 00:52 UTC, PetrischakMaxim reviewed
1. Потом добавим проверку.
2. address строка из обьекта location.
3. price пока что случайное целое положительное число.
4. photos  массив, елемент будет строка путь к картинке `image.jpg`
5. location зарезервированнное слово в js, можно заменить его на подобное.

2022-03-03 00:52 UTC, PetrischakMaxim commented on js/main.js
getRandomInt и getRandomFloat давай вынесем в файл utils.js

2022-03-03 00:52 UTC, PetrischakMaxim commented on js/main.js
> +// Object 1 - Описание автора (аватарка)
Лучше каждое подзадание разбить на функции.
К примеру тут можно сделать функцию генерирования аватарки.
`generateAvatar` как вариант.

2022-03-03 00:52 UTC, PetrischakMaxim commented on js/main.js
> +const typeMas = ['palace', 'flat', 'house', 'bungalow', 'hotel'];
Лучше назвать более понятно к примеру `housingList`  `housingTypes`

2022-03-03 00:52 UTC, PetrischakMaxim commented on js/main.js
> +const type = (elem) => typeMas[getRandomInt(0, typeMas.length - 1)];
`randomHousingType` или что-то подобное

2022-03-03 00:52 UTC, PetrischakMaxim commented on js/main.js
> +const checkinMas = ['12:00', '13:00', '14:00'];
`checkinTimes`

2022-03-03 00:52 UTC, PetrischakMaxim commented on js/main.js
> +const featuresMas = ['wifi', 'dishwashar', 'parking', 'washer', 'elevator', 'conditioner'];
`featuresList`

2022-03-03 00:52 UTC, PetrischakMaxim commented on js/main.js
> +const checkin = (elem) => checkinMas[getRandomInt(0, checkinMas.length - 1)];
Функция должна быть глаголом, `getCheckinTime` как пример

2022-03-03 00:52 UTC, PetrischakMaxim commented on js/main.js
> +const checkout = (elem) => checkinMas[getRandomInt(0, checkinMas.length - 1)];
Функция должна быть глаголом, `getCheckoutTime` как пример

2022-03-03 00:52 UTC, PetrischakMaxim commented on js/main.js
> +  photos: 'Фото',
`photos`, массив строк — массив случайной длины из значений

2022-03-04 10:24 UTC, KletskovG requested changes
Нужно доработать код по генерации массива фич, также во многих местах можно подобрать более подходящие названия

2022-03-04 10:24 UTC, KletskovG commented on js/main.js
> +const generateAvatar = () => {
Чтобы тут eslint не ругался давай сразу после этой функции ее вызовем

2022-03-04 10:24 UTC, KletskovG commented on js/main.js
> +const generateAvatar = () => {
И во всех других местах тоже

2022-03-04 10:24 UTC, KletskovG commented on js/main.js
> +    const photosArr = ['https://assets.htmlacademy.ru/content/intensive/javascript-1/keksobooking/duonguyen-8LrGtIxxa4w.jpg',
Давай перенесем первую ссылку не новую строку для того, чтобы объявление этого массива выглядело однообразно - так намного быстрее можно понять, о чем этот массив

2022-03-04 10:24 UTC, KletskovG commented on js/main.js
> +    while (fea.length < feaLng) {
Весь этот кусок кода можно сделать намного проще, если использовать [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) 

С помощью Set ты сможешь автоматически не добавлять дубли, а также не надо будет писать цикл в цикле, что  сделает твой код намного быстрее

```js
const fea = new Set([]);
const randomFeature = featuresList[getRandomInt(0, featuresList.length-1)]; 
fea.append(randomFeature)

return [...fea]; // Set является на массивом, а iterable-объектом, поэтому надо его привести к массиву
```

2022-03-04 10:24 UTC, KletskovG commented on js/main.js
> +      const elemRand = featuresList[getRandomInt(0, featuresList.length-1)]; // рандомный элемент массива с индексом от 0 до 5
Такое название отражает суть переменной лишь от части, намного более четкое название - `randomFeature`. Оно сразу говорит нам о том, что будет лежать в этой переменной

2022-03-04 10:24 UTC, KletskovG commented on js/main.js
> +    const fea = []; // генерируемый массив
Честно говоря, мне потребовалось много времени, чтобы понять, почему массив называется `fea`

Предлагаю  `features` - так намного понятнее, что тут будет лежать, даже комментарий не нужен

2022-03-04 10:24 UTC, KletskovG commented on js/main.js
> +    const feaLng = getRandomInt(1, featuresList.length); // задаем рандомную длину генерируемому массиву от 1 до 6
Тут можно смело заменить на `featuresLength` - не стесняйся писать слова полностью. От того, что имя переменной будет длиннее, хуже не станет. Главное - чтобы было понятно, для чего эта переменная нужна. 

Опять таки, с подходящим названием комментарий не нужен

В целом, комментарии показывают, что что-то ты не можешь объяснить своим кодом. Это скорее "необходимое зло", к которому нужно иногда прибегать. Но точно не в таких случаях

2022-03-04 10:24 UTC, KletskovG commented on js/main.js
> +  const photos = () => {
В названии функции всегда должен быть глагол. Это и по критериям проекта, и в целом - хорошая практика.

Существительные подходят для переменных

2022-03-04 10:24 UTC, KletskovG commented on js/main.js
> +  const getRandomFeature = () => {
У тебя возвращается массив, поэтому название этой функции должно отражать, что возвращается массив (множественное число)

`getRandomFeatures`

2022-03-05 15:19 UTC, merged